[2024-09-15T21:58:10.021+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-15T21:58:10.191+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: holtzy_etl.load_data scheduled__2024-09-14T00:00:00+00:00 [queued]>
[2024-09-15T21:58:10.200+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: holtzy_etl.load_data scheduled__2024-09-14T00:00:00+00:00 [queued]>
[2024-09-15T21:58:10.211+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 6
[2024-09-15T21:58:10.225+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2024-09-14 00:00:00+00:00
[2024-09-15T21:58:10.230+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=130) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-15T21:58:10.232+0000] {standard_task_runner.py:63} INFO - Started process 139 to run task
[2024-09-15T21:58:10.236+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'holtzy_etl', 'load_data', 'scheduled__2024-09-14T00:00:00+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpdvof0ans']
[2024-09-15T21:58:10.238+0000] {standard_task_runner.py:91} INFO - Job 84: Subtask load_data
[2024-09-15T21:58:10.299+0000] {task_command.py:426} INFO - Running <TaskInstance: holtzy_etl.load_data scheduled__2024-09-14T00:00:00+00:00 [running]> on host ca38a783ff7d
[2024-09-15T21:58:10.399+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fabriciositto' AIRFLOW_CTX_DAG_ID='holtzy_etl' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-14T00:00:00+00:00'
[2024-09-15T21:58:10.400+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-15T21:58:10.415+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-15T21:58:10.416+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/modules/load.py", line 9, in load
    engine=connect_db()
           ^^^^^^^^^^^^
TypeError: 'module' object is not callable
[2024-09-15T21:58:10.435+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=holtzy_etl, task_id=load_data, run_id=scheduled__2024-09-14T00:00:00+00:00, execution_date=20240914T000000, start_date=20240915T215810, end_date=20240915T215810
[2024-09-15T21:58:10.448+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 84 for task load_data ('module' object is not callable; 139)
[2024-09-15T21:58:10.490+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-15T21:58:10.507+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15T21:58:10.510+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
