[2024-09-15T21:57:08.143+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-15T21:57:08.311+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: holtzy_etl.load_data scheduled__2024-09-14T00:00:00+00:00 [queued]>
[2024-09-15T21:57:08.320+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: holtzy_etl.load_data scheduled__2024-09-14T00:00:00+00:00 [queued]>
[2024-09-15T21:57:08.321+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-09-15T21:57:08.335+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2024-09-14 00:00:00+00:00
[2024-09-15T21:57:08.342+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=120) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-15T21:57:08.343+0000] {standard_task_runner.py:63} INFO - Started process 122 to run task
[2024-09-15T21:57:08.343+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'holtzy_etl', 'load_data', 'scheduled__2024-09-14T00:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpexo6xn6f']
[2024-09-15T21:57:08.346+0000] {standard_task_runner.py:91} INFO - Job 83: Subtask load_data
[2024-09-15T21:57:08.394+0000] {task_command.py:426} INFO - Running <TaskInstance: holtzy_etl.load_data scheduled__2024-09-14T00:00:00+00:00 [running]> on host ca38a783ff7d
[2024-09-15T21:57:08.477+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fabriciositto' AIRFLOW_CTX_DAG_ID='holtzy_etl' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-14T00:00:00+00:00'
[2024-09-15T21:57:08.478+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-15T21:57:08.491+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-15T21:57:08.492+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/modules/load.py", line 9, in load
    engine=connect_db()
           ^^^^^^^^^^^^
TypeError: 'module' object is not callable
[2024-09-15T21:57:08.508+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=holtzy_etl, task_id=load_data, run_id=scheduled__2024-09-14T00:00:00+00:00, execution_date=20240914T000000, start_date=20240915T215708, end_date=20240915T215708
[2024-09-15T21:57:08.520+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 83 for task load_data ('module' object is not callable; 122)
[2024-09-15T21:57:08.558+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-15T21:57:08.573+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15T21:57:08.576+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
