[2024-09-15T21:59:11.746+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-15T21:59:11.897+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: holtzy_etl.load_data scheduled__2024-09-14T00:00:00+00:00 [queued]>
[2024-09-15T21:59:11.905+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: holtzy_etl.load_data scheduled__2024-09-14T00:00:00+00:00 [queued]>
[2024-09-15T21:59:11.916+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 6
[2024-09-15T21:59:11.928+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2024-09-14 00:00:00+00:00
[2024-09-15T21:59:11.934+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=147) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-15T21:59:11.936+0000] {standard_task_runner.py:63} INFO - Started process 149 to run task
[2024-09-15T21:59:11.936+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'holtzy_etl', 'load_data', 'scheduled__2024-09-14T00:00:00+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpkmloyj8w']
[2024-09-15T21:59:11.939+0000] {standard_task_runner.py:91} INFO - Job 85: Subtask load_data
[2024-09-15T21:59:11.985+0000] {task_command.py:426} INFO - Running <TaskInstance: holtzy_etl.load_data scheduled__2024-09-14T00:00:00+00:00 [running]> on host ca38a783ff7d
[2024-09-15T21:59:12.065+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fabriciositto' AIRFLOW_CTX_DAG_ID='holtzy_etl' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-14T00:00:00+00:00'
[2024-09-15T21:59:12.066+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-15T21:59:12.119+0000] {warnings.py:112} WARNING - /opt/***/dags/modules/load.py:47: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data.to_sql(

[2024-09-15T21:59:12.122+0000] {logging_mixin.py:188} INFO - The upload could not be completed - module 'modules.connect_db' has no attribute 'cursor'
[2024-09-15T21:59:12.123+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-15T21:59:12.124+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-15T21:59:12.135+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=holtzy_etl, task_id=load_data, run_id=scheduled__2024-09-14T00:00:00+00:00, execution_date=20240914T000000, start_date=20240915T215911, end_date=20240915T215912
[2024-09-15T21:59:12.191+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-15T21:59:12.206+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15T21:59:12.208+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
